PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbc: <http://dbpedia.org/resource/Category:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fm: <http://flandersmake.be/otfc/>
SELECT ?film ?dob ?abstract
WHERE {
    ?film rdfs:comment ?abstract.
    ?film fm:bondActor ?actor.
    ?actor dbo:birthDate ?dob.
    FILTER (LANG(?abstract) = 'en')
}
